
theme = "duckquill"
author = "Davi Almeida"
title="Davi Almeida"
base_url = "https://eletronbius.github.io/"

compile_sass = true

build_search_index = true

taxonomies = [{ name = "tags", feed = true }]
[search]
index_format = "fuse_json"

[extra]
# Put all your custom variables here
emoji_favicon = "🧙‍♂️"
accent_color = "#ff7800"
accent_color_dark = "#ffa348"


[extra.nav]
links = [
	{ url = "@/About/_index.md", name = "About" },
	{ url = "@/Projects/_index.md", name = "Projects" },
    #{ url = "tags", name = "Tags" }
]

[extra.footer]
show_copyright = true
show_powered_by = true
links = [
	{ name = "GitHub",   url = "https://github.com/Eletronbius" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/davialp" },
	{ name = "CV",       url = "cv.pdf" },
]